#!/bin/bash

# Connect to the MySQL server and execute the FLUSH ENGINE LOGS command
mysql -u root -p -e "FLUSH ENGINE LOGS;"

# Initialize the progress bar
echo -ne '#####                     (33%)\r'

# Loop until the log is fully flushed
while true; do

    # Execute the SHOW ENGINE INNODB STATUS command and extract the "Log flushed up to" value
    log_flushed_up_to=$(mysql -u root -p -e "SHOW ENGINE INNODB STATUS\G" | grep "Log flushed up to" | awk '{print $NF}')

    # Check if the log has been fully flushed
    if [[ "$log_flushed_up_to" == *"purged"* ]]; then
        # If the log has been purged, update the progress bar and exit the loop
        echo -ne '#############             (66%)\r'
        break
    else
        # If the log has not been purged, update the progress bar with the percentage completed
        percent_completed=$(( log_flushed_up_to * 100 / $(cat /var/lib/mysql/ib_logfile0 | wc -c) ))
        echo -ne "$percent_completed% complete\r"
    fi

    # Sleep for 1 second before checking the status again
    sleep 1
done

# Display a message indicating that the log has been fully flushed
echo -ne '#######################   (100%)\r'
echo -ne '\n'
echo "Log has been fully flushed."
